name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up environment
              run: |
                  sudo apt-get update
                  sudo apt-get install -y curl bash

            - name: Install Bun
              run: |
                  curl -fsSL https://bun.sh/install | bash
                  echo "$HOME/.bun/bin" >> $GITHUB_PATH

            - name: Verify Bun Installation
              run: bun --version

            - name: Install dependencies
              run: bun install

            - name: Run Prettier
              run: bun run format:check

            - name: Run ESLint
              run: bun run lint:check

            - name: Run TypeScript
              run: bun run type:check

            # - name: Run Tests
            #   run: bun run test
