name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        shell: bash
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export BUN_INSTALL="$HOME/.bun"' >> $GITHUB_ENV
          echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $GITHUB_ENV
        env:
          BUN_INSTALL: $HOME/.bun
          PATH: $BUN_INSTALL/bin:$PATH

      - name: Install dependencies
        run: bun install
        env:
          BUN_INSTALL: ${{ env.BUN_INSTALL }}
          PATH: ${{ env.PATH }}

      - name: Run Prettier
        run: bun run format:check

      - name: Run ESLint
        run: bun run lint

      - name: Run TypeScript
        run: bun run type-check

      # - name: Run Tests
      #   run: bun run test
